# Generated by Django 4.2.16 on 2024-11-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='blank',
            new_name='price',
        ),
    ]
